# Generated by Django 5.2.1 on 2025-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_age_resume_first_name_resume_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(default='Нема', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='loler@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default=666666, max_length=20),
            preserve_default=False,
        ),
    ]
