# Generated by Django 5.2.1 on 2025-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_about_resume_address_resume_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(default='template1', max_length=50),
        ),
    ]
