# Generated by Django 5.2.1 on 2025-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
