# Generated by Django 5.2.1 on 2025-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_templaterating_delete_resumerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resume_photos/'),
        ),
    ]
