# Generated by Django 5.2.1 on 2025-06-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_resume_attachment_resume_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='photo',
        ),
    ]
