# Generated by Django 5.2.1 on 2025-06-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_resume_attachment_resume_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='attachment_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
